### ISSUE TITLE
Error when deploying app to knative

### ISSUE THREAD

**Issue by daisy-ycguo** [serverless/serverless-knative#7]
Error message when `serverless deploy` to knative instance using the sample application:

```
  TypeError: Cannot read property 'code' of undefined
      at KnativeServing.default (/Users/Daisy/workspace/serverless/my-service/node_modules/@serverless/knative-serving/serverless.js:25:34)
```

The commands I run
```
npm install serverless --global
serverless create --template knative-docker --path my-service
cd my-service/
npm install
serverless deploy
```

**Comment by medikoo** [comment]
@daisy-ycguo this looks as a bug in https://github.com/serverless-components/knative-serving can you post it there?

**Comment by daisy-ycguo** [comment]
ok. posted here: https://github.com/serverless-components/knative-serving/issues/3
Close this issue then.
